name: Deploy

on:
  push:
    branches: [testing/new-github-actions]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Connect to EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd Death-Star/
          git pull origin testing/new-github-actions
          npm install
          npm run build
          mkdir estuveaqui
          pm2 delete all 
          ls
          pm2 start npm -- start
