name: CIDD

on:
  push:
    branches: [feature/fix-components-box]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: #ésto solo se usa para probar en una rama específica
          ref: feature/fix-components-box

      - name: Install dependencies
        run: npm install

      - name: Create .env
        run: |
          echo "NEXT_PUBLIC_JWT_EXPIRATION=${{ secrets.NEXT_PUBLIC_JWT_EXPIRATION }}" > .env
          echo "NEXT_PUBLIC_JWT_SECRET=${{ secrets.NEXT_PUBLIC_JWT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET=${{ secrets.NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET }}" >> .env

          echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> .env
          echo "AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}" >> .env
          echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env

          echo "NEXT_PUBLIC_MANDALORE=${{ secrets.NEXT_PUBLIC_MANDALORE }}" >> .env
          echo "NEXT_PUBLIC_CORUSCANT=${{ secrets.NEXT_PUBLIC_CORUSCANT }}" >> .env
          echo "NEXT_PUBLIC_CURRENT_URL=${{ secrets.NEXT_PUBLIC_CURRENT_URL }}" >> .env

      - name: Build app
        run: npm run build

      - name: Run build
        run: npm run start
