name: CIDD

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Use Node.js v18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.16.0'
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Clean and install dependencies
        run: |
          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi
          npm install

      - name: Create .env
        run: |
          echo "NEXT_PUBLIC_JWT_EXPIRATION=${{ secrets.NEXT_PUBLIC_JWT_EXPIRATION }}" > .env
          echo "NEXT_PUBLIC_JWT_SECRET=${{ secrets.NEXT_PUBLIC_JWT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET=${{ secrets.NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET }}" >> .env

          echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> .env
          echo "AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}" >> .env
          echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env

          echo "NEXT_PUBLIC_MANDALORE=${{ secrets.NEXT_PUBLIC_MANDALORE }}" >> .env
          echo "NEXT_PUBLIC_CORUSCANT=${{ secrets.NEXT_PUBLIC_CORUSCANT }}" >> .env
          echo "NEXT_PUBLIC_CURRENT_URL=${{ secrets.NEXT_PUBLIC_CURRENT_URL }}" >> .env

      - name: Build app
        run: npm run build

      - name: Run App
        run: npm run start &

      # - name: PM2 delete all
      #   run: pm2 delete all --silent

      # - name: Run build
      #   run: pm2 start npm -- start
